# open api 3.10 spec
openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
  description: Library API
  contact:
    name: John Doe
    email: uno@cualquiera.com
    url: https://www.cualquiera.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /books:
    get:
      summary: Get all books
      description: Get all books
      operationId: getBooks
      tags:
        - books
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

